### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by D1abloRUS** [D1abloRUS/proxycheck-server#1]
- [ ] рефакторинг

- [x] демон для парсинга файла

- [x] get list country

- [x] отдвать статус, прокси, id=?, json life/dead

- [x] добавить в выдачу id поле
